package main

// NEEDCAPS

func cliche(match string) *BadTerm {
	return &BadTerm{match, "'%s' is a cliche. Avoid it like the plague."}
}

// ShouldNotCliche returns a slice of BadTerm's, none of which should be in the
// a text (case insensitive). See existence_checks.go for details of BadTerms.
func ShouldNotCliche() []TextCheck {
	return []TextCheck{
		cliche("all hell broke loose"),
		cliche("american as apple pie"),
		cliche("hobson's choice"),
		cliche("i beg to differ"),
		cliche("jack of all trades"),
		cliche("a chip off the old block"),
		cliche("a clean slate"),
		cliche("a dark and stormy night"),
		cliche("a far cry"),
		cliche("a fate worse than death"),
		cliche("a fine kettle of fish"),
		cliche("a loose cannon"),
		cliche("a matter of concern"),
		cliche("a penny saved is a penny earned"),
		cliche("a tough row to hoe"),
		cliche("a word to the wise"),
		cliche("ace in the hole"),
		cliche("acid test"),
		cliche("add insult to injury"),
		cliche("against all odds"),
		cliche("air your dirty laundry"),
		cliche("alas and alack"),
		cliche("all fun and games"),
		cliche("all in a day's work"),
		cliche("all talk, no action"),
		cliche("all things being equal"),
		cliche("all thumbs"),
		cliche("all your eggs in one basket"),
		cliche("all's fair in love and war"),
		cliche("all's well that ends well"),
		cliche("almighty dollar"),
		cliche("an axe? to grind"),
		cliche("another day, another dollar"),
		cliche("armed to the teeth"),
		cliche("as a last resort"),
		cliche("as luck would have it"),
		cliche("as old as time"),
		cliche("as the crow flies"),
		cliche("at loose ends"),
		cliche("at my wits end"),
		cliche("at the end of the day"),
		cliche("attached hereto"),
		cliche("avoid like the plague"),
		cliche("babe in the woods"),
		cliche("back against the wall"),
		cliche("back in the saddle"),
		cliche("back to square one"),
		cliche("back to the drawing board"),
		cliche("bad to the bone"),
		cliche("badge of honor"),
		cliche("bald faced liar"),
		cliche("bald-faced lie"),
		cliche("ballpark figure"),
		cliche("banging your head against a brick wall"),
		cliche("baptism by fire"),
		cliche("barking up the wrong tree"),
		cliche("bat out of hell"),
		cliche("be all and end all"),
		cliche("beat a dead horse"),
		cliche("beat around the bush"),
		cliche("been there, done that"),
		cliche("beggars can't be choosers"),
		cliche("behind the eight ball"),
		cliche("bend over backwards"),
		cliche("benefit of the doubt"),
		cliche("bent out of shape"),
		cliche("best thing since sliced bread"),
		cliche("bet your bottom dollar"),
		cliche("better half"),
		cliche("better late than never"),
		cliche("better mousetrap"),
		cliche("better safe than sorry"),
		cliche("between scylla and charybdis"),
		cliche("between a rock and a hard place"),
		cliche("between a rock and a hard place"),
		cliche("between the devil and the deep blue sea"),
		cliche("betwixt and between"),
		cliche("beyond the pale"),
		cliche("bide your time"),
		cliche("big as life"),
		cliche("big cheese"),
		cliche("big fish in a small pond"),
		cliche("big man on campus"),
		cliche("bigger they are the harder they fall"),
		cliche("bird in the hand"),
		cliche("bird's eye view"),
		cliche("birds and the bees"),
		cliche("birds of a feather flock together"),
		cliche("bit the hand that feeds you"),
		cliche("bite the bullet"),
		cliche("bite the dust"),
		cliche("bitten off more than he can chew"),
		cliche("black as coal"),
		cliche("black as pitch"),
		cliche("black as the ace of spades"),
		cliche("blast from the past"),
		cliche("bleeding heart"),
		cliche("blessing in disguise"),
		cliche("blind ambition"),
		cliche("blind as a bat"),
		cliche("blind leading the blind"),
		cliche("blissful ignorance"),
		cliche("blood is thicker than water"),
		cliche("blood sweat and tears"),
		cliche("blow a fuse"),
		cliche("blow off steam"),
		cliche("blow your own horn"),
		cliche("blushing bride"),
		cliche("boils down to"),
		cliche("bolt from the blue"),
		cliche("bone to pick"),
		cliche("bored stiff"),
		cliche("bored to tears"),
		cliche("bottomless pit"),
		cliche("boys will be boys"),
		cliche("bright and early"),
		cliche("brings home the bacon"),
		cliche("broad across the beam"),
		cliche("broken record"),
		cliche("brought back to reality"),
		cliche("bulk large"),
		cliche("bull by the horns"),
		cliche("bull in a china shop"),
		cliche("burn the midnight oil"),
		cliche("burning question"),
		cliche("burning the candle at both ends"),
		cliche("burst your bubble"),
		cliche("bury the hatchet"),
		cliche("busy as a bee"),
		cliche("but that's another story"),
		cliche("by hook or by crook"),
		cliche("by no means"),
		cliche("call a spade a spade"),
		cliche("called onto the carpet"),
		cliche("calm before the storm"),
		cliche("can of worms"),
		cliche("can't cut the mustard"),
		cliche("can't hold a candle to"),
		cliche("case of mistaken identity"),
		cliche("cast aspersions"),
		cliche("cat got your tongue"),
		cliche("cat's meow"),
		cliche("caught in the crossfire"),
		cliche("caught red-handed"),
		cliche("chase a red herring"),
		cliche("checkered past"),
		cliche("chomping at the bit"),
		cliche("cleanliness is next to godliness"),
		cliche("clear as a bell"),
		cliche("clear as mud"),
		cliche("close to the vest"),
		cliche("cock and bull story"),
		cliche("cold shoulder"),
		cliche("come hell or high water"),
		cliche("comparing apples and oranges"),
		cliche("conspicuous by its absence"),
		cliche("conspicuous by its absence"),
		cliche("cool as a cucumber"),
		cliche("cool, calm, and collected"),
		cliche("cost a king's ransom"),
		cliche("count your blessings"),
		cliche("crack of dawn"),
		cliche("crash course"),
		cliche("creature comforts"),
		cliche("cross that bridge when you come to it"),
		cliche("crushing blow"),
		cliche("cry like a baby"),
		cliche("cry me a river"),
		cliche("cry over spilt milk"),
		cliche("crystal clear"),
		cliche("crystal clear"),
		cliche("curiosity killed the cat"),
		cliche("cut and dried"),
		cliche("cut through the red tape"),
		cliche("cut to the chase"),
		cliche("cute as a bugs ear"),
		cliche("cute as a button"),
		cliche("cute as a puppy"),
		cliche("cuts to the quick"),
		cliche("cutting edge"),
		cliche("dark before the dawn"),
		cliche("day in, day out"),
		cliche("dead as a doornail"),
		cliche("decision-making process"),
		cliche("devil is in the details"),
		cliche("dime a dozen"),
		cliche("divide and conquer"),
		cliche("dog and pony show"),
		cliche("dog days"),
		cliche("dog eat dog"),
		cliche("dog tired"),
		cliche("don't burn your bridges"),
		cliche("don't count your chickens"),
		cliche("don't look a gift horse in the mouth"),
		cliche("don't rock the boat"),
		cliche("don't step on anyone's toes"),
		cliche("don't take any wooden nickels"),
		cliche("down and out"),
		cliche("down at the heels"),
		cliche("down in the dumps"),
		cliche("down the hatch"),
		cliche("down to earth"),
		cliche("draw the line"),
		cliche("dressed to kill"),
		cliche("dressed to the nines"),
		cliche("drives me up the wall"),
		cliche("dubious distinction"),
		cliche("dull as dishwater"),
		cliche("duly authorized"),
		cliche("dyed in the wool"),
		cliche("eagle eye"),
		cliche("ear to the ground"),
		cliche("early bird catches the worm"),
		cliche("easier said than done"),
		cliche("easier said than done"),
		cliche("easy as pie"),
		cliche("eat your heart out"),
		cliche("eat your words"),
		cliche("eleventh hour"),
		cliche("enclosed herewith"),
		cliche("even the playing field"),
		cliche("every dog has its day"),
		cliche("every fiber of my being"),
		cliche("everything but the kitchen sink"),
		cliche("eye for an eye"),
		cliche("eyes peeled"),
		cliche("face the music"),
		cliche("facts of life"),
		cliche("fair weather friend"),
		cliche("fall by the wayside"),
		cliche("fan the flames"),
		cliche("far be it from me"),
		cliche("fast and loose"),
		cliche("feast or famine"),
		cliche("feather your nest"),
		cliche("feathered friends"),
		cliche("few and far between"),
		cliche("fifteen minutes of fame"),
		cliche("fills the bill"),
		cliche("filthy vermin"),
		cliche("fine kettle of fish"),
		cliche("first and foremost"),
		cliche("fish out of water"),
		cliche("fishing for a compliment"),
		cliche("fit as a fiddle"),
		cliche("fit the bill"),
		cliche("fit to be tied"),
		cliche("flash in the pan"),
		cliche("flat as a pancake"),
		cliche("flip your lid"),
		cliche("flog a dead horse"),
		cliche("fly by night"),
		cliche("fly the coop"),
		cliche("follow your heart"),
		cliche("for all intents and purposes"),
		cliche("for free"),
		cliche("for the birds"),
		cliche("for what it's worth"),
		cliche("force of nature"),
		cliche("force to be reckoned with"),
		cliche("forgive and forget"),
		cliche("fox in the henhouse"),
		cliche("free and easy"),
		cliche("free as a bird"),
		cliche("fresh as a daisy"),
		cliche("full steam ahead"),
		cliche("fun in the sun"),
		cliche("garbage in, garbage out"),
		cliche("gentle as a lamb"),
		cliche("get a kick out of"),
		cliche("get a leg up"),
		cliche("get down and dirty"),
		cliche("get the lead out"),
		cliche("get to the bottom of"),
		cliche("get with the program"),
		cliche("get your feet wet"),
		cliche("gets my goat"),
		cliche("gilding the lily"),
		cliche("gilding the lily"),
		cliche("give and take"),
		cliche("go against the grain"),
		cliche("go at it tooth and nail"),
		cliche("go for broke"),
		cliche("go him one better"),
		cliche("go the extra mile"),
		cliche("go with the flow"),
		cliche("goes without saying"),
		cliche("good as gold"),
		cliche("good deed for the day"),
		cliche("good things come to those who wait"),
		cliche("good time was had by all"),
		cliche("good times were had by all"),
		cliche("greased lightning"),
		cliche("greek to me"),
		cliche("green thumb"),
		cliche("green-eyed monster"),
		cliche("grist for the mill"),
		cliche("growing like a weed"),
		cliche("hair of the dog"),
		cliche("hand to mouth"),
		cliche("happy as a clam"),
		cliche("happy as a lark"),
		cliche("hasn't a clue"),
		cliche("have a nice day"),
		cliche("have a short fuse"),
		cliche("have high hopes"),
		cliche("have the last laugh"),
		cliche("haven't got a row to hoe"),
		cliche("he's got his hands full"),
		cliche("head honcho"),
		cliche("head over heels"),
		cliche("hear a pin drop"),
		cliche("heard it through the grapevine"),
		cliche("heart's content"),
		cliche("heavy as lead"),
		cliche("hem and haw"),
		cliche("high and dry"),
		cliche("high and mighty"),
		cliche("high as a kite"),
		cliche("his own worst enemy"),
		cliche("his work cut out for him"),
		cliche("hit paydirt"),
		cliche("hither and yon"),
		cliche("hold your head up high"),
		cliche("hold your horses"),
		cliche("hold your own"),
		cliche("hold your tongue"),
		cliche("honest as the day is long"),
		cliche("horns of a dilemma"),
		cliche("horns of a dilemma"),
		cliche("horse of a different color"),
		cliche("hot under the collar"),
		cliche("hour of need"),
		cliche("icing on the cake"),
		cliche("if and when"),
		cliche("if the shoe fits"),
		cliche("if the shoe were on the other foot"),
		cliche("if you catch my drift"),
		cliche("in a jam"),
		cliche("in a jiffy"),
		cliche("in a nutshell"),
		cliche("in a pig's eye"),
		cliche("in a pinch"),
		cliche("in a word"),
		cliche("in hot water"),
		cliche("in light of"),
		cliche("in reference to"),
		cliche("in short supply"),
		cliche("in the final analysis"),
		cliche("in the foreseeable future"),
		cliche("in the gutter"),
		cliche("in the last analysis"),
		cliche("in the long run"),
		cliche("in the matter of"),
		cliche("in the nick of time"),
		cliche("in the thick of it"),
		cliche("in your dreams"),
		cliche("innocent bystander"),
		cliche("it ain't over till the fat lady sings"),
		cliche("it goes without saying"),
		cliche("it stands to reason"),
		cliche("it takes all kinds"),
		cliche("it takes one to know one"),
		cliche("it's a small world"),
		cliche("it's not what you know, it's who you know"),
		cliche("it's only a matter of time"),
		cliche("ivory tower"),
		cliche("jockey for position"),
		cliche("jog your memory"),
		cliche("joined at the hip"),
		cliche("judge a book by its cover"),
		cliche("jump down your throat"),
		cliche("jump in with both feet"),
		cliche("jump on the bandwagon"),
		cliche("jump the gun"),
		cliche("jump to conclusions"),
		cliche("just a hop, skip, and a jump"),
		cliche("just the ticket"),
		cliche("justice is blind"),
		cliche("keep a stiff upper lip"),
		cliche("keep an eye on"),
		cliche("keep it simple, stupid"),
		cliche("keep the home fires burning"),
		cliche("keep up with the joneses"),
		cliche("keep your chin up"),
		cliche("keep your fingers crossed"),
		cliche("kick the bucket"),
		cliche("kick up your heels"),
		cliche("kick your feet up"),
		cliche("kid in a candy store"),
		cliche("kill two birds with one stone"),
		cliche("kiss of death"),
		cliche("knock it out of the park"),
		cliche("knock on wood"),
		cliche("knock your socks off"),
		cliche("know him from adam"),
		cliche("know the ropes"),
		cliche("know the score"),
		cliche("knuckle down"),
		cliche("knuckle sandwich"),
		cliche("knuckle under"),
		cliche("labor of love"),
		cliche("ladder of success"),
		cliche("land on your feet"),
		cliche("lap of luxury"),
		cliche("last but not least"),
		cliche("last but not least"),
		cliche("last hurrah"),
		cliche("last-ditch effort"),
		cliche("law of the jungle"),
		cliche("law of the land"),
		cliche("lay down the law"),
		cliche("leaps and bounds"),
		cliche("let sleeping dogs lie"),
		cliche("let the cat out of the bag"),
		cliche("let the good times roll"),
		cliche("let your hair down"),
		cliche("let's talk turkey"),
		cliche("letter perfect"),
		cliche("lick your wounds"),
		cliche("lies like a rug"),
		cliche("life's a bitch"),
		cliche("life's a grind"),
		cliche("light at the end of the tunnel"),
		cliche("lighter than a feather"),
		cliche("lighter than air"),
		cliche("like clockwork"),
		cliche("like father like son"),
		cliche("like taking candy from a baby"),
		cliche("like there's no tomorrow"),
		cliche("lion's share"),
		cliche("live and learn"),
		cliche("live and let live"),
		cliche("long and short of it"),
		cliche("long lost love"),
		cliche("look before you leap"),
		cliche("look down your nose"),
		cliche("look what the cat dragged in"),
		cliche("looking a gift horse in the mouth"),
		cliche("looks like death warmed over"),
		cliche("loose cannon"),
		cliche("lose your head"),
		cliche("lose your temper"),
		cliche("loud as a horn"),
		cliche("lounge lizard"),
		cliche("loved and lost"),
		cliche("low man on the totem pole"),
		cliche("luck of the irish"),
		cliche("luck of the draw"),
		cliche("make a mockery of"),
		cliche("make hay while the sun shines"),
		cliche("make money hand over fist"),
		cliche("make my day"),
		cliche("make the best of a bad situation"),
		cliche("make the best of it"),
		cliche("make your blood boil"),
		cliche("male chauvinism"),
		cliche("man of few words"),
		cliche("man's best friend"),
		cliche("many and diverse"),
		cliche("mark my words"),
		cliche("meaningful dialogue"),
		cliche("missed the boat on that one"),
		cliche("moment in the sun"),
		cliche("moment of glory"),
		cliche("moment of truth"),
		cliche("moment of truth"),
		cliche("money to burn"),
		cliche("more in sorrow than in anger"),
		cliche("more power to you"),
		cliche("more sinned against than sinning"),
		cliche("more than one way to skin a cat"),
		cliche("movers and shakers"),
		cliche("moving experience"),
		cliche("my better half"),
		cliche("naked as a jaybird"),
		cliche("naked truth"),
		cliche("neat as a pin"),
		cliche("needle in a haystack"),
		cliche("needless to say"),
		cliche("neither here nor there"),
		cliche("never look back"),
		cliche("never say never"),
		cliche("nip and tuck"),
		cliche("nip in the bud"),
		cliche("nip it in the bud"),
		cliche("no guts, no glory"),
		cliche("no love lost"),
		cliche("no pain, no gain"),
		cliche("no skin off my back"),
		cliche("no stone unturned"),
		cliche("no time like the present"),
		cliche("no use crying over spilled milk"),
		cliche("nose to the grindstone"),
		cliche("not a hope in hell"),
		cliche("not a minute's peace"),
		cliche("not in my backyard"),
		cliche("not playing with a full deck"),
		cliche("not the end of the world"),
		cliche("not written in stone"),
		cliche("nothing to sneeze at"),
		cliche("nothing ventured nothing gained"),
		cliche("now we're cooking"),
		cliche("off the top of my head"),
		cliche("off the wagon"),
		cliche("off the wall"),
		cliche("old hat"),
		cliche("olden days"),
		cliche("older and wiser"),
		cliche("older than methuselah"),
		cliche("older than dirt"),
		cliche("on a roll"),
		cliche("on cloud nine"),
		cliche("on pins and needles"),
		cliche("on the bandwagon"),
		cliche("on the money"),
		cliche("on the nose"),
		cliche("on the right track"),
		cliche("on the rocks"),
		cliche("on the same page"),
		cliche("on the spot"),
		cliche("on the tip of my tongue"),
		cliche("on the wagon"),
		cliche("on thin ice"),
		cliche("once bitten, twice shy"),
		cliche("one bad apple doesn't spoil the bushel"),
		cliche("one born every minute"),
		cliche("one brick short"),
		cliche("one foot in the grave"),
		cliche("one in a million"),
		cliche("one red cent"),
		cliche("only game in town"),
		cliche("open a can of worms"),
		cliche("open and shut case"),
		cliche("open the flood gates"),
		cliche("opportunity doesn't knock twice"),
		cliche("out of pocket"),
		cliche("out of sight, out of mind"),
		cliche("out of the frying pan into the fire"),
		cliche("out of the woods"),
		cliche("out on a limb"),
		cliche("over a barrel"),
		cliche("over the hump"),
		cliche("pain and suffering"),
		cliche("pain in the"),
		cliche("panic button"),
		cliche("par for the course"),
		cliche("par for the course"),
		cliche("part and parcel"),
		cliche("party pooper"),
		cliche("pass the buck"),
		cliche("patience is a virtue"),
		cliche("pay through the nose"),
		cliche("penny pincher"),
		cliche("perfect storm"),
		cliche("pig in a poke"),
		cliche("pile it on"),
		cliche("pillar of the community"),
		cliche("pin your hopes on"),
		cliche("pitter patter of little feet"),
		cliche("plain as day"),
		cliche("plain as the nose on your face"),
		cliche("play by the rules"),
		cliche("play your cards right"),
		cliche("playing the field"),
		cliche("playing with fire"),
		cliche("please feel free to"),
		cliche("pleased as punch"),
		cliche("plenty of fish in the sea"),
		cliche("point with pride"),
		cliche("poor as a church mouse"),
		cliche("pot calling the kettle black"),
		cliche("presidential timber"),
		cliche("pretty as a picture"),
		cliche("pull a fast one"),
		cliche("pull your punches"),
		cliche("pulled no punches"),
		cliche("pulling your leg"),
		cliche("pure as the driven snow"),
		cliche("pursuant to your request"),
		cliche("put it in a nutshell"),
		cliche("put one over on you"),
		cliche("put the cart before the horse"),
		cliche("put the pedal to the metal"),
		cliche("put your best foot forward"),
		cliche("put your foot down"),
		cliche("quantum jump"),
		cliche("quantum leap"),
		cliche("quick as a bunny"),
		cliche("quick as a lick"),
		cliche("quick as a wink"),
		cliche("quick as lightning"),
		cliche("quiet as a dormouse"),
		cliche("rags to riches"),
		cliche("raining buckets"),
		cliche("raining cats and dogs"),
		cliche("rank and file"),
		cliche("rat race"),
		cliche("reap what you sow"),
		cliche("red as a beet"),
		cliche("red herring"),
		cliche("redound to one's credit"),
		cliche("redound to the benefit of"),
		cliche("regarding the matter of"),
		cliche("reinvent the wheel"),
		cliche("rich and famous"),
		cliche("rings a bell"),
		cliche("ripe old age"),
		cliche("ripped me off"),
		cliche("rise and shine"),
		cliche("road to hell is paved with good intentions"),
		cliche("rob peter to pay paul"),
		cliche("roll over in the grave"),
		cliche("rub the wrong way"),
		cliche("ruled the roost"),
		cliche("running in circles"),
		cliche("sad but true"),
		cliche("sadder but wiser"),
		cliche("salt of the earth"),
		cliche("scared stiff"),
		cliche("scared to death"),
		cliche("sea change"),
		cliche("sealed with a kiss"),
		cliche("second to none"),
		cliche("see eye to eye"),
		cliche("seen the light"),
		cliche("seize the day"),
		cliche("set the record straight"),
		cliche("set the world on fire"),
		cliche("set your teeth on edge"),
		cliche("sharp as a tack"),
		cliche("shirked his duties"),
		cliche("shoot for the moon"),
		cliche("shoot the breeze"),
		cliche("shot in the dark"),
		cliche("shoulder to the wheel"),
		cliche("sick as a dog"),
		cliche("sigh of relief"),
		cliche("signed, sealed, and delivered"),
		cliche("sink or swim"),
		cliche("six of one, half a dozen of another"),
		cliche("six of one, half a dozen of the other"),
		cliche("skating on thin ice"),
		cliche("slept like a log"),
		cliche("slinging mud"),
		cliche("slippery as an eel"),
		cliche("slow as molasses"),
		cliche("slowly but surely"),
		cliche("smart as a whip"),
		cliche("smooth as a baby's bottom"),
		cliche("sneaking suspicion"),
		cliche("snug as a bug in a rug"),
		cliche("sow wild oats"),
		cliche("spare the rod, spoil the child"),
		cliche("speak of the devil"),
		cliche("spilled the beans"),
		cliche("spinning your wheels"),
		cliche("spitting image of"),
		cliche("spoke with relish"),
		cliche("spread like wildfire"),
		cliche("spring to life"),
		cliche("squeaky wheel gets the grease"),
		cliche("stands out like a sore thumb"),
		cliche("start from scratch"),
		cliche("stick in the mud"),
		cliche("still waters run deep"),
		cliche("stitch in time"),
		cliche("stop and smell the roses"),
		cliche("straight as an arrow"),
		cliche("straw that broke the camel's back"),
		cliche("stretched to the breaking point"),
		cliche("strong as an ox"),
		cliche("stubborn as a mule"),
		cliche("stuff that dreams are made of"),
		cliche("stuffed shirt"),
		cliche("sweating blood"),
		cliche("sweating bullets"),
		cliche("take a load off"),
		cliche("take one for the team"),
		cliche("take the bait"),
		cliche("take the bull by the horns"),
		cliche("take the plunge"),
		cliche("takes one to know one"),
		cliche("takes two to tango"),
		cliche("than you can shake a stick at"),
		cliche("the cream of the crop"),
		cliche("the cream rises to the top"),
		cliche("the more the merrier"),
		cliche("the real mccoy"),
		cliche("the real deal"),
		cliche("the red carpet treatment"),
		cliche("the same old story"),
		cliche("the straw that broke the camel's back"),
		cliche("there is no accounting for taste"),
		cliche("thick as a brick"),
		cliche("thick as thieves"),
		cliche("thick as thieves"),
		cliche("thin as a rail"),
		cliche("think outside of the box"),
		cliche("thinking outside the box"),
		cliche("third time's the charm"),
		cliche("this day and age"),
		cliche("this hurts me worse than it hurts you"),
		cliche("this point in time"),
		cliche("this will acknowledge"),
		cliche("thought leaders?"),
		cliche("three sheets to the wind"),
		cliche("through thick and thin"),
		cliche("throw in the towel"),
		cliche("throw the baby out with the bathwater"),
		cliche("tie one on"),
		cliche("tighter than a drum"),
		cliche("time and time again"),
		cliche("time is of the essence"),
		cliche("tip of the iceberg"),
		cliche("tired but happy"),
		cliche("to coin a phrase"),
		cliche("to each his own"),
		cliche("to make a long story short"),
		cliche("to the best of my knowledge"),
		cliche("toe the line"),
		cliche("tongue in cheek"),
		cliche("too good to be true"),
		cliche("too hot to handle"),
		cliche("too numerous to mention"),
		cliche("touch with a ten foot pole"),
		cliche("tough as nails"),
		cliche("trial and error"),
		cliche("trials and tribulations"),
		cliche("tried and true"),
		cliche("trip down memory lane"),
		cliche("twist of fate"),
		cliche("two cents worth"),
		cliche("two peas in a pod"),
		cliche("ugly as sin"),
		cliche("under the counter"),
		cliche("under the gun"),
		cliche("under the same roof"),
		cliche("under the weather"),
		cliche("until the cows come home"),
		cliche("unvarnished truth"),
		cliche("up the creek"),
		cliche("uphill battle"),
		cliche("upper crust"),
		cliche("upset the applecart"),
		cliche("vain attempt"),
		cliche("vain effort"),
		cliche("vanquish the enemy"),
		cliche("various and sundry"),
		cliche("vested interest"),
		cliche("viable alternative"),
		cliche("waiting for the other shoe to drop"),
		cliche("wakeup call"),
		cliche("warm welcome"),
		cliche("watch your p's and q's"),
		cliche("watch your tongue"),
		cliche("watching the clock"),
		cliche("water under the bridge"),
		cliche("wax eloquent"),
		cliche("wax poetic"),
		cliche("we are pleased to advice"),
		cliche("we regret to inform you"),
		cliche("we wish to state"),
		cliche("we've got a situation here"),
		cliche("weather the storm"),
		cliche("weed them out"),
		cliche("week of sundays"),
		cliche("went belly up"),
		cliche("wet behind the ears"),
		cliche("what goes around comes around"),
		cliche("what you see is what you get"),
		cliche("when it rains, it pours"),
		cliche("when push comes to shove"),
		cliche("when the cat's away"),
		cliche("when the going gets tough, the tough get going"),
		cliche("whet (?:the|your) appetite"),
		cliche("white as a sheet"),
		cliche("whole ball of wax"),
		cliche("whole hog"),
		cliche("whole nine yards"),
		cliche("wild goose chase"),
		cliche("will wonders never cease?"),
		cliche("wisdom of the ages"),
		cliche("wise as an owl"),
		cliche("wolf at the door"),
		cliche("wool pulled over our eyes"),
		cliche("words fail me"),
		cliche("work like a dog"),
		cliche("world weary"),
		cliche("worst nightmare"),
		cliche("worth its weight in gold"),
		cliche("writ large"),
		cliche("wrong side of the bed"),
		cliche("yanking your chain"),
		cliche("yappy as a dog"),
		cliche("years young"),
		cliche("you are hereby advised that"),
		cliche("you are what you eat"),
		cliche("you can run but you can't hide"),
		cliche("you only live once"),
		cliche("you're the boss "),
		cliche("young and foolish"),
		cliche("young and vibrant"),
	}
}
