# tint is pretty simple, so we handle test/build with dmk instead of
# a full-blown Makefile

# Base config for all our outputs below
# Note that we assume a step writes a signal file named after the step
build-step:
    abstract: true
    delOnFail: true
    direct: true
    inputs:
        - "*.go"
    outputs:
        - ".${DMK_STEPNAME}"

test:
    command: "./script/test && touch .${DMK_STEPNAME}"
    baseStep: build-step

build:
    command: "go build && touch .${DMK_STEPNAME}"
    baseStep: build-step
    inputs:
        - .test
    outputs:
        - tint

# Only runs if explicitly run on command line
# Note that we don't use the base step since it sets explicit=false
bench:
    command: "./script/bench && touch .${DMK_STEPNAME}"
    explicit: true
    direct: true
    delOnFail: true
    inputs:
        - "*.go"
        - .test
        - .build
    outputs:
        - .bench

