package main

// NEEDCAPS

/*
* WARNING: This file contains some extremely offensive words. Actual code
* begins on line 100. I'm not kidding, some of these are really vile.
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
 */

// ShouldNotProfane returns a slice of BadTerm's, none of which should be in the
// a text (case insensitive).
func ShouldNotProfane() []TextCheck {
	return []TextCheck{
		&BadTerm{"abbo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"abeed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"abid", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"abo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"africoon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"alligator bait", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"alligatorbait", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"amateur", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"analannie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"angry", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"anus", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"arabush", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"arabushs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"argie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"armo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"armos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"aroused", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asian", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assbagger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assblaster", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assclown", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asscowboy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asshat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asshole", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assholes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asshore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assjockey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asskiss", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asskisser", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assklown", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asslick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asslicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asslover", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assmonkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assmunch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assmuncher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asspacker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asspirate", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asspuppies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"assranger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asswhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"asswipe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"backdoorman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"badfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"balllicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"balls", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"banging", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"barface", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"barfface", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bazongas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bazooms", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beanbag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beaner", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beaners", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beaney", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beaneys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beastial", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beatoff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"beatyourmeat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"biatch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bicurious", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bigass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bigbastard", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bigbutt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bisexual", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitcher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitches", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitchez", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitchin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitching", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitchslap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bitchy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"blackman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"blacks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"blowjob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bluegum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bluegums", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boang", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boche", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boches", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bogan", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bohunk", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boner", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boobies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boobs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"booby", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boody", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boong", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boonga", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boongas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boongs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boonies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bootlip", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bootlips", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"booty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bootycall", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bosch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bosche", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bosches", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"boschs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buddhahead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buddhaheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bugger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buggered", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buggery", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bullcrap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bulldike", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bulldyke", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bullshit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bumblefuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bumfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bung", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bunga", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bungas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"bunghole", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buried", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"burr head", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"burr heads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"burrhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"burrheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"butchbabes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"butchdike", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"butchdyke", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"butt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttbang", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttface", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttfuckers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"butthead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttmunch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttmuncher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttpirate", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttplug", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"buttstain", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"byatch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cacker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"camel jockey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"camel jockeys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cameljockey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cameltoe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"carpetmuncher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chav", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cheese eating surrender monkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cheese eating surrender monkies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cheeseeating surrender monkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cheeseeating surrender monkies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cherrypopper", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chickslick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"china swede", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"china swedes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chinaman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chinamen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chinaswede", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chinaswedes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ching chong", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ching chongs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chingchong", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chingchongs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chink", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chinks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chinky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"choad", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chode", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chonkies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chonky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chonkys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"christ killer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"christ killers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chug", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chugs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chunger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chungers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chunkies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chunky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"chunkys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"clamdigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"clamdiver", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"clansman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"clansmen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"clanswoman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"clanswomen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"clogwog", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cock", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockblock", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockblocker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockcowboy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockfight", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockknob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocklicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocklover", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocknob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockqueen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cockrider", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksmith", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksmoker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksucer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksucked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocksucking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocktail", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cocktease", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cohee", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"colored", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coloured", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"commie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"condom", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coolie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coolies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cooly", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coon ass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coon asses", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coonass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coonasses", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coondog", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"coons", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cornhole", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crack", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crackpipe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crapola", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crapper", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crappy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crotch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crotchmonkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"crotchrot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumbubble", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumfest", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumjockey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumm", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cummer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumming", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumquat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumqueen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cumshot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cunn", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cunntt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cunt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cunteyed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cuntfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cuntfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cuntlick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cuntlicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cuntlicking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cuntsucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"curry muncher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"curry munchers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"currymuncher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"currymunchers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cushi", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cushis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"cyberslimer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dago", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dagos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dahmer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dammit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"damn", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"darkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"darkeys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"darkie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"darkies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"darky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"datnigga", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"deapthroat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"deepthroat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dego", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"degos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"demon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"deth", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"diaper head", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"diaper heads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"diaperhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"diaperheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dickbrain", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dickforbrains", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dickhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dickless", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dicklick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dicklicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dickman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dickwad", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dickweed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dike", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dildo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dingleberry", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dix", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dixiedike", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dixiedyke", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"doggiestyle", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"doggystyle", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dong", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"doodoo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dot head", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dot heads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dothead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dotheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dragqueen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dragqween", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dripdick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dumbass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dumbbitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dumbfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dune coon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dune coons", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dyefly", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"dyke", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"easyslut", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"eatballs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"eatme", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"eatpussy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"esqua", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"evl", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"excrement", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"exkwew", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"facefucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fagging", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"faggot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fagot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fannyfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fastfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fatah", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fatass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fatfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fatfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fatso", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fckcum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"felch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"felcher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"felching", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"feltch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"feltcher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"feltching", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fingerfood", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fingerfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fingerfucked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fingerfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fingerfuckers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fingerfucking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fister", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fistfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fistfucked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fistfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fistfucking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fisting", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"flydie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"flydye", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"footaction", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"footfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"footfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"footlicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"footstar", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"forni", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"freakfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"freakyfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"freefuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fubar", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fucck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fucka", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckable", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckbag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckbook", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckbuddy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fucked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckedup", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckface", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckfest", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckfreak", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckfriend", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckina", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fucking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckingbitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckinnuts", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckinright", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckknob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckme", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckmehard", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckmonkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckoff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckpig", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fucks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fucktard", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckwhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuckyou", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fudgepacker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fugly", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuk", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"funfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"fuuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gable", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gangbang", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gangbanged", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gangbanger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gator bait", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gatorbait", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gaymuthafuckinwhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gaysex", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"geezer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ginzo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ginzos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gipp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gippo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gippos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gipps", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"girls", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"givehead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"godammit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goddamit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goddammit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goddamn", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goddamned", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goddamnes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goddamnit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goddamnmuthafucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"golliwog", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"golliwogs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gonzagas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gook eye", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gook eyes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gook", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gookeye", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gookeyes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gookies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gooks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gooky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gora", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goras", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gotohell", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"goyim", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"greaseball", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"greaseballs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"greaser", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"greasers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gringo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gringos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"groe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"groid", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"groids", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"grostulation", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gub", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gubba", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gubbas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gubs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"guinea", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"guineas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"guizi", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gummer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gwailo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gwailos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gweilo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gweilos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyopo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyopos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyped", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gypo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gypos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gypp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gypped", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyppie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyppies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyppo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyppos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyppy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gyppys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gypsies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gypsy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"gypsys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hadji", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hadjis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hairyback", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hairybacks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"haji", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hajis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hajji", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hajjis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"half breed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"half caste", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"halfbreed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"halfcaste", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"handjob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"haole", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"haoles", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hapa", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"harder", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hardon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"harem", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"headfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"headlights", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hebe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hebephila", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hebephile", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hebephiles", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hebephilia", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hebephilic", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hebes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"heeb", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"heebs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hillbillies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hillbilly", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hindoo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hiscock", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hitlerism", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hitlerist", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ho", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hodgie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hoes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"holestuffer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"homobangers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"honger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"honkers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"honkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"honkeys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"honkie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"honkies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"honky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hook", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hooker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hookers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hooters", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hori", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"horis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hork", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"horn", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"horney", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"horniest", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"horny", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"horseshit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hosejob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hoser", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hotdamn", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hotpussy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hottotrot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hummer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hussy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hustler", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hymie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"hymies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"iblowu", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ikes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ikey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ikeymo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ikeymos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ikwe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"illegals", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"indon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"indons", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"injun", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"injuns", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"insest", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"intheass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"inthebuff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"itch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jackass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jackoff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jackshit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jacktheripper", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"japcrap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"japie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"japies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"japs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jebus", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jeez", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jerkoff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jerries", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jerry", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jewed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jewess", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jewish", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiga", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigaboo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigaboos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigarooni", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigaroonis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigg", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigga", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiggabo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiggabos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiggas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiggs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiggy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jigs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jijjiboo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jijjiboos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jimfish", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jism", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jiz", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jizim", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jizjuice", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jizm", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jizz", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jizzim", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jizzum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jugs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jungle bunnies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"jungle bunny", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"junglebunny", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kacap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kacapas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kacaps", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kaffer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kaffir", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kaffre", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kafir", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kanake", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"katsap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"katsaps", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"khokhol", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"khokhols", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kike", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kikes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kissass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"knockers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kondum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"koon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"krap", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"krappy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kraut", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"krauts", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kuffar", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kumbubble", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kumbullbe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kummer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kumming", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kums", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kunilingus", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kunnilingus", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kunt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kushi", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kushis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kwa", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kwai lo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kwai los", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kyke", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kykes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kyopo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"kyopos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lebo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lebos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lesbo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lez", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lezbo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lezz", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lezzo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lickme", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"limey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"limpdick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"limy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"livesex", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lovebone", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lovegoo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lovegun", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lovejuice", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lovemuscle", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lovepistol", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"loverocket", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lowlife", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lubejob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lubra", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lucifer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"luckycammeltoe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lugan", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lugans", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"lynch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mabuno", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mabunos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"macaca", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"macacas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mad", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mahbuno", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mahbunos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mams", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"manhater", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"manpaste", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mattressprincess", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mau mau", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mau maus", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"maumau", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"maumaus", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"meatbeatter", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mgger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mggor", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mickeyfinn", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"milf", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mockey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mockie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mocky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mofo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"moky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"moneyshot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"moon cricket", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"moon crickets", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mooncricket", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mooncrickets", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"moskal", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"moskals", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mosshead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafucka", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafuckaz", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafucked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafuckin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafucking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mothafuckings", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"motherfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"motherfucked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"motherfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"motherfuckin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"motherfucking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"motherfuckings", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"motherlovebone", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"muff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"muffdive", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"muffdiver", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"muffindiver", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mufflikcer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mulatto", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"muncher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"munt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mzungu", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"mzungus", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nastybitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nastyho", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nastyslut", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nastywhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"necro", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"negres", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"negress", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"negro", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"negroes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"negroid", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"negros", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nig", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigar", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigars", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigerian", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigerians", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigette", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigettes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigg", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigga", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggah", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggahs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggar", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggaracci", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggard", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggarded", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggarding", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggardliness", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggardlinesss", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggardly", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggards", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggars", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggaz", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggerhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggerhole", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggle", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggled", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggles", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggling", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigglings", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggor", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggress", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggresses", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigguh", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigguhs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggur", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niggurs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"niglet", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nignog", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigor", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigors", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigr", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigra", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigras", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigre", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigres", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigress", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nigs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nip", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nittit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nlgger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nlggor", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nofuckingway", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nook", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nookey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nookie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"noonan", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nooner", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nudger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"nutfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ontherag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"paddy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"paki", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pakis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pancake face", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pancake faces", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pansies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pansy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"panti", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"payo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pearlnecklace", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pecker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"peckerwood", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"peehole", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"peepee", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"peepshow", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"peepshpw", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pendy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"penetration", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"peni5", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"perv", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phonesex", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phuk", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phuked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phuking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phukked", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phukking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phungky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"phuq", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pi55", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"picaninny", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"piccaninny", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pickaninnies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pickaninny", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"piefke", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"piefkes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"piker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pikey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"piky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pimp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pindick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"piss", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pissed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pisser", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pisses", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pisshead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pissin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pissing", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pissoff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pocha", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pochas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pocho", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pochos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pocketpool", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pohm", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pohms", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"polack", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"polacks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pollock", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pollocks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pom", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pommie grant", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pommie grants", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pommie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pommies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pommy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"poms", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"poo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"poon", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"poontang", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pooper", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"poorwhitetrash", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"popimp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"porch monkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"porch monkies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"porchmonkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pornflick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pornking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"porno", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pornprincess", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"prairie nigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"prairie niggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pric", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"prick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"prickhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"primetime", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pros", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"protestant", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pu55i", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pu55y", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pube", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pubiclice", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pud", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pudboy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pudd", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"puddboy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"puntang", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"purinapricness", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"puss", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussycat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussyeater", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussyfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussylicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussylips", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussylover", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pussypounder", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"pusy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"quashie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"que", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"queef", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"queer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"quickie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"quim", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ra8s", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"raghead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ragheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"redleg", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"redlegs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"redskin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"redskins", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"reestie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"rentafuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"rere", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"ribbed", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"rigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"rimjob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"rimming", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"round eyes", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"roundeye", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"russki", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"russkie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sadis", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sadom", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sambo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sambos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"samckdaddy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sand nigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sand niggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sandm", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sandnigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"scag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"scallywag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"schlong", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"schvartse", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"schvartsen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"schwartze", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"schwartzen", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"screwyou", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"scum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"seppo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"seppos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"septic", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"septics", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"servant", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexfarm", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexhound", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexhouse", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexkitten", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexpot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sextogo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexwhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexymoma", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sexyslim", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shaggin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shagging", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shav", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shawtypimp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sheeney", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shhit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shinola", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitcan", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitdick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shite", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shiteater", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shited", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitface", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitfaced", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitfit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitforbrains", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitfull", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shithapens", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shithappens", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shithead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shithouse", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shiting", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitlist", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitola", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitoutofluck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shits", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitstain", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitted", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitter", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitting", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shitty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shortfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shylock", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"shylocks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sissy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sixsixsix", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sixtynine", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sixtyniner", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skank", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skankbitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skankfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skankwhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skanky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skankybitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skankywhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skinflute", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skum", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skumbag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skwa", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"skwe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slant", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slanteye", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slanty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slapper", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slav", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slavedriver", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sleezebag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sleezeball", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slideitin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slimeball", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slimebucket", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slopehead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slopeheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sloper", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slopers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slopey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slopeys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slopies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slopy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slut", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sluts", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slutt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slutting", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slutty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slutwear", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"slutwhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"smackthemonkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"smut", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"snatch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"snatchpatch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"snigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sniggered", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sniggering", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sniggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"snowback", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"snownigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sodomise", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sodomite", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sodomize", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sonofabitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sonofbitch", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sooties", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sooty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spaghettibender", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spaghettinigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spankthemonkey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spearchucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spearchuckers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spermbag", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spermhearder", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spermherder", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spic", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spicks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spics", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spig", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spigotty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spik", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"splittail", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spooge", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spreadeagle", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spunk", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"spunky", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"sqeh", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"squa", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"squarehead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"squareheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"squaw", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"squinty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"stagg", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"stiffy", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"stringer", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"stripclub", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"stuinties", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"stupidfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"stupidfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"suckdick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"suckme", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"suckmyass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"suckmydick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"suckmytit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"suckoff", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"swamp guinea", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"swamp guineas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tacohead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tacoheads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tar babies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tar baby", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tarbaby", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tard", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"thicklip", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"thicklips", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"thirdeye", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"thirdleg", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"threesome", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"threeway", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"timber nigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"timber niggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"timbernigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tit", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titbitnipply", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titfuck", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titfucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titfuckin", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titjob", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titlicker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titlover", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tits", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tittie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titties", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"titty", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tongethruster", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tonguethrust", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tonguetramp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tosser", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"towel head", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"towel heads", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"towelhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"trailertrash", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tramp", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"trannie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tranny", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"transvestite", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"triplex", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"trots", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tuckahoe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"tunneloflove", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"turd", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"twat", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"twink", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"twinkie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"twobitwhore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"uncle tom", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"unfuckable", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"upskirt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"uptheass", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"upthebutt", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"virginbreaker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wab", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wank", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wanker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wanking", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"waysted", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"weenie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"weewee", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"welcher", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wetb", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wetback", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wetbacks", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wetspot", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whacker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whash", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whiggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whiskeydick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whiskydick", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"white trash", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whitenigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whitetrash", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whitey", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whiteys", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whities", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whop", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whore", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whorefucker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"whorehouse", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wigga", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wiggas", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wigger", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wiggers", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"williewanker", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wog", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wogs", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wop", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wuss", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"wuzzie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"xkwe", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"xxx", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"yarpie", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"yarpies", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"yellowman", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"yid", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"yids", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"zigabo", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"zigabos", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"zipperhead", "'%s' is profane or offensive. DO NOT USE."},
		&BadTerm{"zipperheads", "'%s' is profane or offensive. DO NOT USE."},
	}
}
